server {
    listen 80;
    server_name kingvcam.com www.kingvcam.com _;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name kingvcam.com www.kingvcam.com;
    merge_slashes on;

    ssl_certificate /etc/letsencrypt/live/kingvcam.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kingvcam.com/privkey.pem;

    location / {
        rewrite "^/+(.*)$" /$1 break;
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
